version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:730288119321:task-definition/fargate-taskdef:3"
        LoadBalancerInfo:
          ContainerName: "aws-code-pipeline"
          ContainerPort: "5000"
        PlatformVersion: "LATEST"
